name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build (macOS)
        run: |
          xcodebuild \
            -project Vault.xcodeproj \
            -target Vault \
            -configuration Debug \
            -destination 'platform=macOS' \
            CODE_SIGNING_ALLOWED=NO \
            build
